---

- name: Firewall firewalld haproxy
  block:
  - name: Allow haproxy statsistics frontend
    ansible.posix.firewalld:
      rich_rule: "rule family='ipv4' port port='{{ haproxy_statsistics_port }}' protocol='tcp' accept"
      zone: 'public'
      state: enabled
      permanent: yes
      immediate: yes
    when: haproxy_statsistics_allowed_ips | length > 0

  # To fix
  # - name: Allow haproxy service frontend
  #   ansible.posix.firewalld:
  #     rich_rule: "rule family='ipv4' port port='{{ haproxy_service_config[item].haproxy.port }}' protocol='tcp' accept"
  #     zone: 'public'
  #     state: enabled
  #     permanent: yes
  #     immediate: yes
  #   when: haproxy_service_config[item].haproxy.port is defined
  #   loop: "{{ haproxy_service_config | list }}"

  # - name: Allow haproxy service frontend
  #   # ansible.posix.firewalld:
  #   debug:
  #     msg: rich_rule="rule family='ipv4' port port='{{ item }}' protocol='tcp' accept"
  #     # zone: 'insaservices'
  #     # state: enabled
  #     # permanent: yes
  #     # immediate: yes
  #   loop: "{{ haproxy_service_config | list }}"
  #   when: haproxy_service_config[item].haproxy.ports is defined

  when: which_firewall == "firewalld"
  tags: haproxy

