---

- name: Firewall firewalld haproxy
  block:
  - name: set default firewalld zone
    set_fact:
    firewalld_zones: 
        - public
    when: firewalld_zones is not defined

  - name: Allow haproxy statsistics frontend
    ansible.posix.firewalld:
      rich_rule: "rule family='ipv4' port port='{{ haproxy_statsistics_port }}' protocol='tcp' accept"
      zone: "{{ item }}"
      state: enabled
      permanent: yes
      immediate: yes
    loop: "{{ firewalld_zones | list }}"
    when: haproxy_statsistics_allowed_ips | length > 0

  - name: Allow haproxy services over firewalld zones
    include_tasks: fw_haproxy_firewalld_services.yml
    loop_control:
      loop_var: fw_zone_item
    loop: "{{ firewalld_zones | list }}"

  when: which_firewall == "firewalld"
  tags: haproxy

