---
- name: Allow haproxy service 'ports'
  ansible.posix.firewalld:
    rich_rule: "rule family='ipv4' destination address={{ lookup('community.general.dig', item.0 ) }} port port='{{ item.1 }}' protocol='tcp' accept"
    zone: "{{ fw_zone_item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ haproxy_service_config | list | product ( haproxy_service_config | list | map('extract', haproxy_service_config) | map(attribute='haproxy.ports') | flatten ) | list }}"
  when: haproxy_service_config[item.0].haproxy.ports is defined